#!/bin/bash

USER_NAME=cause

# STANDARD USERS
# Standard users are recorded in /etc/passwd and /etc/group
# Creating users as part of the container build ensures these files won't drift
#useradd -G wheel -u 1000 -K SUB_GID_MIN=1000001 -K SUB_UID_MIN=1000001 $USER_NAME
#echo "Temp#SsaP" | passwd $USER_NAME -s

# SYSTEMD-HOMED USERS
# systemd-homed users are created by firstboot-setup during the initial boot, as they need systemd to be running
# Setup subuid & subgid for the systemd-homed user
echo "$USER_NAME:1000001:65536">/etc/subuid
echo "$USER_NAME:1000001:65536">/etc/subgid

# Setup initial password for root
ROOT_HASH="$y$j9T$mXUAYoDa2pKhfLJu6xQqI/$9Xx8oh0gLi5y.2iTy2s9mqIJm9BLXJRg7rubNJX8.U6"
echo "root:$ROOT_HASH" | chpasswd -e